feat: rpc-handler
ubiquibot/command-wallet pull request #14
Opened 2024-08-18 15:07 UTC by gentlementlegen

Resolves #3

2024-08-18 17:01 UTC, 0x4007 commented on CHANGELOG.md
Nice to have, but seems tedious for other people to update unless they use the same, presumably automated tooling that you use.

2024-08-18 17:13 UTC, gentlementlegen commented on CHANGELOG.md
The changelog is automatically generated by `release-please` based on the commits inside this repository. It is here because it gets generated on the main branch but I hadn't merged it back in `development`. But this should not manually edited.

2024-08-24 09:55 UTC, Keyrxng approved these changes

2024-08-25 06:05 UTC, 0x4007 requested changes

2024-08-25 06:05 UTC, 0x4007 commented on src/handlers/query-wallet.ts
> +    tracking: "none",
```suggestion
```
Really doesn't matter especially non client side.

2024-08-25 09:54 UTC, merged